
```{r load}

dados <- read_xls("~/Documents/Google Drive/office/orçamento2017.xls", 
                  sheet = "inv")

dados <- dados[,c(1:5)]

avi.dados <- subset(dados, dono=="avi")
bob.dados <- subset(dados, dono=="bob")

# unique(dados$dono)
```

# Evolução de cada investimento

```{r bob-all}

bob.dados <- bob.dados[,c(2:5)]

data.wide <- dcast(bob.dados,
                   data + nome ~ operação, fun.aggregate = sum) %>%
        arrange(nome, data)
  


### acertando cdb
condicao <- data.wide$data == as.Date("2017-06-21") & data.wide$nome == "CDB 5A 123P"
data.wide$investimento[condicao] <- 5923.95

condicao <- data.wide$data < as.Date("2017-06-21") & 
        data.wide$nome %in% c("CDB 5A 123P", "PREFIX 19")

data.wide$investimento[condicao] <- 0
data.wide$saque[condicao] <- 0


#acertando prefix 19

condicao <- data.wide$data == as.Date("2017-06-21") & 
                data.wide$nome == "PREFIX 19"
data.wide$investimento[condicao] <- 11664.76



rendimentos <- group_by(data.wide, nome) %>%
        # filter(data >= "2017-03-01") %>%
        mutate(d.investido = cumsum(investimento) + cumsum(saque)) %>%
        filter(atual != 0 & investimento==0) %>%
        mutate(crescimento = round(
                100*(atual+saque- d.investido)/d.investido,
                2)
               ) %>%
        select(c("nome", "data", "crescimento")) %>%
        filter(abs(crescimento) < 100) %>%
        arrange(nome, data)

condicao <- rendimentos$data > as.Date("2017-09-20") & 
        rendimentos$nome == "PREFIX 19"
rendimentos$crescimento[condicao] <- 0


data.wide <- dcast(bob.dados,
                   data + nome ~ operação, fun.aggregate = sum) %>%
        arrange(nome, data)


acumulado <- group_by(data.wide,nome) %>% 
        summarise(d.investido = sum(investimento) + sum(saque),
                  renda = atual[data==max(data)] - (d.investido)) %>%
        filter(d.investido > 0)


investido <- sum(acumulado$d.investido)
investido


renda <- sum(acumulado$renda)

investido - renda
```




```{r}
 
# rendimentos %>%
# # totais.show %>%
#         kable("html", caption = "Crescimento de cada aplicação") %>%
#         kable_styling(bootstrap_options = c("striped", "hover"))

```


```{r}
plot <- ggplot(rendimentos, aes(data, crescimento, color=nome, 
                                text = as.Date(data))) + geom_line()

ggplotly(plot, tooltip = "text")
```

