<br>

## Evolução 


### Movimentação mensal

```{r results='asis'}

mov.mensal <- df[,c(2:7)] %>% group_by(data) %>% 
        summarise(entrada = sum(investimento), saida = sum(saque))

mov.mensal <- xts(mov.mensal[,-1], order.by = mov.mensal$data) %>% na.locf()

mov.mensal$saida <- -1* mov.mensal$saida

mov.mensal <- apply.monthly(mov.mensal, sum)

# mov.mensal.df <- fortify(mov.mensal["2017-08/"])
# names(mov.mensal.df) <- c("Index", "mov.mensal")


mov.mensal.df <- mov.mensal %>% fortify() %>% melt(id.vars="Index") %>% 
        mutate(Index = as.Date(Index),
               value = round(value,3)
               )  


mov.mensal.plot <- nPlot(value ~ Index,
                     # data = mov.mensal.df, type = 'lineWithFocusChart')
                     data = mov.mensal.df, type = 'scatterChart')

mov.mensal.plot$xAxis( tickFormat="#!function(d) {
                    if (typeof d === 'string') {
                        d = parseFloat(d);
                    }
                    return d3.time.format('%d-%m-%y')(new Date(d*86400000));;
                }
        !#" )

mov.mensal.plot$show("inline", include_assets = TRUE, cdn = TRUE)

# mov.mensal.df %>% ggplot(aes(Index, mov.mensal))+
#         geom_point(stat = "identity") + 
#         geom_text(aes(label=mov.mensal, size=4)) +
#         ggtitle("Saldo Atual de cada fundo (R$)") +
#         theme_economist() + scale_fill_economist() +
#         tema 


```




```{r}
# evolução da carteira

##### Saldo final

saldo.final <- df[,c(2,3,7)]

# spread para ter as mesmas datas em todos os fundos
saldo.final <- dcast(saldo.final, data ~ fundo) 

# transforma em xts para usar locf
# preenche os NAs com o último valor
saldo.final <- xts(saldo.final[,-1], order.by = saldo.final$data) %>% na.locf()

# preenche NAs restantes com 0
saldo.final[is.na.data.frame(saldo.final)] <- 0 

# melt de volta, para então agrupar por data e ter 
# um sumarize do saldo por dia
saldo.final %<>% fortify() %>% melt(id.vars = "Index") %>% 
        group_by(Index) %>% 
        summarize(valor = sum(value))

saldo.final <- xts(saldo.final[,-1], order.by = saldo.final$Index)    
###### dinheiro investido


cria.serie <- function(df) {
        
        serie <- dcast(df, data ~ fundo)

        # preenche NAs restantes com 0
        serie[is.na.data.frame(serie)] <- 0 
        
        serie[,-1] <- apply(serie[,-1], 2, function(x) cumsum(x))
        
        # melt de volta, para então agrupar por data e ter 
        # um sumarize do saldo por dia
        serie %<>% melt(id.vars = "data") %>% 
                group_by(data) %>% 
                summarize(valor = sum(value))
        
        serie <- xts(serie[,-1], order.by = serie$data)
        serie
}

investimento <- cria.serie(df[,c(2,3,5)])
saque <- cria.serie(df[,c(2,3,6)])

# investimento <- saldo.final - (saldo.final + saque - investimento)
investimento <- investimento - saque


carteira <- merge.xts(saldo.final, investimento)
names(carteira) <- c("Total", "Investimento")

ev.carteira <- carteira["2017-06/"] %>% fortify() %>% melt(id.vars="Index") %>% 
        mutate(Index = as.Date(Index),
               value = round(value,3)
               )  


```

### Evolução da carteira



```{r results="asis"}
# nvd3 plot for account evolution
ev.carteira.plot <- nPlot(value ~ Index, group = 'variable', 
                     data = ev.carteira, type = 'lineWithFocusChart')

ev.carteira.plot$xAxis( tickFormat="#!function(d) { 
                    if (typeof d === 'string') {
                        d = parseFloat(d);
                    }
                    return d3.time.format('%d-%m-%y')(new Date(d*86400000));;
                }
        !#" )
ev.carteira.plot$show("inline", include_assets = TRUE, cdn = TRUE)

# ev.carteira.plot$print(include_assets=T)



# ggplot
# plot1 <- ggplot(plot.df, 
#                aes(Index, value, color=variable)
#                    # text = paste(value, "<br>", Index)
#                    # )
#                ) +
#         geom_line() + 
#         ggtitle("Evolução da carteira (R$)") +
#         labs(y="", x="") + 
#         theme_economist() + scale_fill_economist()
#         # theme(legend.position="bottom", legend.direction="horizontal",
#         #            legend.title = element_blank()) 
# 
# # ggplotly(plot1, tooltip = c("Index", "value"), 800, 400)

```

<br>

### Evolução dos investimentos

```{r}
# evolução de rendimentos
df %<>% group_by(fundo) %>%  arrange(fundo, data)

evolucao <- mutate(df,
                invest.liq = cumsum(investimento) - cumsum(saque),
                crescimento = round(
                        100*(saldoF-invest.liq)/cumsum(investimento),
                        2),
                meses = as.numeric(data - min(data))/(24*3600*30),
                cresc.pond = as.numeric(abs(crescimento)^(1/meses)*
                        ifelse(crescimento<0,-1,1))
                )
                

# preparando para xts
# dcast para colocar cada fundo em um vetor

data.wide <- dcast(evolucao[,c(2,3,11)], 
                   data ~ fundo, value.var = "cresc.pond")


# transformar em xts agora senão na.locf tranforma tudo em char
df.xts <- xts(data.wide[, c(2:ncol(data.wide))], order.by = data.wide$data)


df.xts <- na.locf(df.xts) # preenche os NAs com o último valor
df.xts[is.na.data.frame(df.xts)] <- 0 # preenche NAs restantes com 0


# transformar de volta pra df, enviar para ggplot
df.wide <- fortify(df.xts["2017-06/"])
# df.wide <- fortify(df.xts)


ev.investimentos <- melt(df.wide, id.vars = "Index") %>% 
        mutate(Index = as.Date(Index),
               value = round(value,3)
               ) 
#creating colors for each var
# colourCount <- length(unique(ev.investimentos$variable))
# paleta <- colorRampPalette(brewer.pal(colourCount, "Set1"))
# colors <- paleta(colourCount)
# 
# ev.investimentos$colors <- colors[ev.investimentos$variable]

      
        
 
```


```{r results="asis"}
# nvd3 plot for evolution of each asset
ev.investimentos.plot <- nPlot(value ~ Index, group = 'variable', 
                     data = ev.investimentos, type = 'lineWithFocusChart')

ev.investimentos.plot$xAxis( tickFormat="#!function(d) { 
                    if (typeof d === 'string') {
                        d = parseFloat(d);
                    }
                    return d3.time.format('%d-%m-%y')(new Date(d*86400000));;
                }
        !#" )
ev.investimentos.plot$show("inline", include_assets = TRUE, cdn = TRUE)
# ev.investimentos.plot$print(include_assets=T)



# plot.ev.mensal <-  ggplot(df.melt,
#                 aes(Index, value, color=variable,
#                    text = paste(round(value,2), "<br>", as.Date(Index))
#                    )
#                ) +
#         geom_line() + 
#         ggtitle("Evolução dos rendimentos (%)") +
#         labs(y="Crestimento %", x="") + 
#         theme_economist() + scale_fill_economist()
#         # theme(legend.position="bottom", legend.direction="horizontal",
#         #            legend.title = element_blank()) 

# ggplotly(plot.ev.mensal, tooltip = "text", 800, 400)
# plot.ev.mensal

```

<br>

