---
title: "Personal Financial Investments Analysis"
author: "erickfis@gmail.com"
date: "`r format(Sys.time(), '%Y %B, %d')`"

output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
    toc: true
    self_contained: no


---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)


library(knitr)
library(rmarkdown)
library(dplyr)
library(lubridate)
library(ggplot2)
library(readxl)
library(reshape2)
library(plotly)
library(kableExtra)
library(xts)
library(broom)

options(knitr.table.format = "html") 


```

```{r load}

dados <- read_xls("~/Documents/Google Drive/office/orçamento2017.xls", 
                  sheet = "inv")

dados <- dados[,c(1:5)]

avi.dados <- subset(dados, dono=="avi")
bob.dados <- subset(dados, dono=="bob")

# unique(dados$dono)
```

# Investimentos do Bob

```{r bob-all}

bob.dados <- bob.dados[,c(2:5)]

# data.wide <- dcast(w500, 
#                    data ~ operação,
#                    value.var="valor")

data.wide <- dcast(bob.dados,
                   data + nome ~ operação, fun.aggregate = sum) %>%
        arrange(nome, data)
  

# data.wide <- dcast(bob.dados, 
#                    data + nome ~ operação, 
#                    value.var = "valor", fun.aggregate = x) %>%
#         arrange(nome, data)


### acertando cdb
condicao <- data.wide$data == as.Date("2017-06-21") & data.wide$nome == "CDB 5A 123P"
data.wide$investimento[condicao] <- 5923.95

condicao <- data.wide$data < as.Date("2017-06-21") & 
        data.wide$nome %in% c("CDB 5A 123P", "PREFIX 19")

data.wide$investimento[condicao] <- 0
data.wide$saque[condicao] <- 0


#acertando prefix 19

condicao <- data.wide$data == as.Date("2017-06-21") & 
                data.wide$nome == "PREFIX 19"
data.wide$investimento[condicao] <- 11664.76

# condicao <- data.wide$data == as.Date("2017-09-21") & 
#                 data.wide$nome == "PREFIX 19"
# data.wide$atual[condicao] <- 8236.77







# 
# ###cdb
# meses <- as.numeric(as.Date("2017-12-05") - as.Date("2016-04-11"))/30
# dif <- 6198.48 - 5000
# 
# rend <- dif/meses
# rend/5000
# 
#            
# ###lci
# 
# 
# meses <- as.numeric(as.Date("2017-05-26") - as.Date("2017-12-05"))/30
# dif <- 10557.31 - 10000
# 
# rend <- dif/meses
# rend/10000







rendimentos <- group_by(data.wide, nome) %>%
        # filter(data >= "2017-03-01") %>%
        mutate(d.investido = cumsum(investimento) + cumsum(saque)) %>%
        filter(atual != 0 & investimento==0) %>%
        mutate(crescimento = round(
                100*(atual+saque- d.investido)/d.investido,
                2)
               ) %>%
        select(c("nome", "data", "crescimento")) %>%
        filter(abs(crescimento) < 100) %>%
        arrange(nome, data)



condicao <- rendimentos$data > as.Date("2017-09-20") & 
        rendimentos$nome == "PREFIX 19"
rendimentos$crescimento[condicao] <- 0


```






```{r}
# 
# rendimentos %>%
# # totais.show %>% 
#         kable("html", caption = "Rendimento para cada aplicação") %>% 
#         kable_styling(bootstrap_options = c("striped", "hover"))

```


```{r}
plot <- ggplot(rendimentos, aes(data, crescimento, color=nome, 
                                text = as.Date(data))) + geom_line()

ggplotly(plot, tooltip = "text")
```


## Crescimento de cada um por modelo linear

```{r}

# ###wa500
# w500 <- subset(rendimentos, nome == "WA500")
# w500$indice <- 1:nrow(w500)
# 
# fitW500 <- lm(rendimento ~ indice -1, w500)
# 
# ### cdb
# indice <- grep("^CDB", rendimentos$nome)
# cdb <- rendimentos[indice,]
# cdb$indice <- 1:nrow(cdb)
# 
# fitCDB <- lm(rendimento ~ indice -1, cdb)
# summary(fit)
# 
# ### lci
# indice <- grep("^LCI", rendimentos$nome)
# lci <- rendimentos[indice,]
# lci$indice <- 1:nrow(lci)
# 
# fitLCI <- lm(rendimento ~ indice -1, lci)



```


# Análise de lag

```{r}

data.wide <- dcast(rendimentos, 
                   data ~ nome, value.var = "crescimento")
                   
dados <- xts(data.wide[, c(2:9)], order.by = data.wide$data)


dados <- na.locf(dados)

dados[is.na.data.frame(dados)] <- 0


# dados["2017-06/"]

dados.diff <- diff.xts(dados)


plot.xts(dados.diff, legend.loc = "bottomright", auto.legend=TRUE)

plot.xts(dados.diff[,c(2,5,8)], legend.loc = "bottomright", auto.legend=TRUE)

# autoplot(dados.diff, sca)


# # data.wide[, c(2:9)] <- sapply(data.wide[, c(2:9)], as.numeric)
# 
# sapply(seq_along(nomes.corretos), 
#        function(x)
#                 nome.familia[nome.familia == nomes.errados[x]] <<- 
#                                                 nomes.corretos[x]
# )


```



```{r}

df <- fortify(dados.diff["2017-07/"])

df.melt <- melt(df, id.vars = "Index")




t.dados <- tidy(dados.diff["2017-07/"])


plot2 <- ggplot(t.dados, aes(x=index,y=value, color=series,
                   # text = paste(index, "<br>",
                   #              "investimento: ", series, "<br>",
                   #              "crescimento: ", value)
                   # ))
                   # text = paste(as.Date(index), "<br>", value, "<br>", series)))
              text = as.Date(index))) + geom_line()


# plot2 <- ggplot(t.dados, aes(x=index,y=value, color=series)) +
#                             geom_line()


# plot2 <- plot2 + geom_line()

ggplotly(plot2, tooltip = "text")

```




# Avi


```{r avi-all}

avi.all <- avi.dados[,c(2:5)]

data.wide <- dcast(avi.all, 
                   data + nome ~ operação, fun.aggregate = sum)
                   

rendimentos <- group_by(data.wide, nome) %>%
        mutate(d.investido = cumsum(investimento) + cumsum(saque)) %>%
        filter(atual != 0 & investimento==0) %>%
        mutate(rendimento = round(
                100*(atual+saque- d.investido)/d.investido,
                2)
               ) %>%
        select(c("nome", "data", "rendimento")) %>%
        filter(abs(rendimento) < 100) %>%
        arrange(nome, data)




```



```{r}

rendimentos %>%
# totais.show %>% 
        kable("html", caption = "Rendimento para cada aplicação") %>% 
        kable_styling(bootstrap_options = c("striped", "hover"))

```


```{r}
plot <- ggplot(rendimentos, aes(data, rendimento, color=nome)) + 
        geom_line()

ggplotly(plot)
```



# comparando w500 e lci

```{r}
plot <- ggplot(rendimentos[grep("^WA|^LCI", rendimentos$nome),], aes(data, rendimento, color=nome)) + 
        geom_line()

plot
ggplotly(plot)
```

